### ISSUE TITLE
Missing trainset link

### ISSUE THREAD

**Issue by Baber-Jan** [Chloe-Liu33/Locust-mini#1]
Can you please update the trainset link. Right now it is same as test link

**Comment by Chloe-Liu33** [comment]
Hi Baber, 

Thanks for your email. Sorry for the mistake and I have revised the trainset link and updated it in github. Please feel free to reach out if you have any other questions or concerns.

Kind Regards

**Comment by Chloe-Liu33** [comment]
> Baber
Hi Baber,

Thanks for your email. Sorry for the mistake and I have revised the trainset link and updated it in github. Please feel free to reach out if you have any other questions or concerns.

Kind Regard

**Comment by Baber-Jan** [comment]
Thank you, can you please also check the Locust 2 and Locust 3 datasets in the test set. They have same files in images and gt.

**Comment by Chloe-Liu33** [comment]
Note that Locust 2 in the testset is the testset in this project,  all images (just for demo) in Locust 3 are included in Locust 2 in testset. So, you can ignore Locust 3.

**Comment by Baber-Jan** [comment]
Thank you
